#Nainstaluj R packages
install.packages("dplyr", repos = "http://cran.us.r-project.org")
install.packages("data.table", repos = "http://cran.us.r-project.org")
install.packages("tidyr", repos = "http://cran.us.r-project.org")
install.packages("zoo", repos = "http://cran.us.r-project.org")
install.packages("readxl", repos = "http://cran.us.r-project.org")
install.packages("janitor", repos = "http://cran.us.r-project.org")
install.packages("stringr", repos = "http://cran.us.r-project.org") 
install.packages("fuzzyjoin", repos = "http://cran.us.r-project.org")
install.packages("lubridate", repos = "http://cran.us.r-project.org") 
#install.packages("rstudioapi", repos = "http://cran.us.r-project.org")
install.packages("fuzzyjoin", repos = "http://cran.us.r-project.org")
